#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 125
#define LARGE_STATE_COUNT 16
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 12

enum {
  anon_sym_POUND_LBRACK = 1,
  aux_sym_annotation_token1 = 2,
  anon_sym_RBRACK = 3,
  sym_comment = 4,
  anon_sym_ = 5,
  anon_sym_LF = 6,
  anon_sym_CR = 7,
  anon_sym_TAB = 8,
  anon_sym_LBRACE_RBRACE = 9,
  anon_sym_LBRACE = 10,
  anon_sym_RBRACE = 11,
  anon_sym_LBRACK_LBRACK = 12,
  anon_sym_EQ = 13,
  anon_sym_BANG_EQ = 14,
  anon_sym_LT_EQ = 15,
  anon_sym_LT = 16,
  anon_sym_GT_EQ = 17,
  anon_sym_GT = 18,
  sym_digits = 19,
  aux_sym_number_token1 = 20,
  sym_identifier = 21,
  anon_sym_value_COLON = 22,
  anon_sym_PIPE = 23,
  anon_sym_DOLLAR = 24,
  anon_sym_AT = 25,
  anon_sym_COLON = 26,
  sym_quoted = 27,
  anon_sym_AT_LBRACK = 28,
  aux_sym_inline_arithmetic_token1 = 29,
  anon_sym_AT_BSLASH_LBRACK = 30,
  sym_source_file = 31,
  aux_sym__ws = 32,
  sym__list = 33,
  sym__list_item = 34,
  sym_list = 35,
  sym_if_list = 36,
  sym_statement = 37,
  sym_operator = 38,
  sym__bvalue = 39,
  sym__lvalue = 40,
  sym__rvalue = 41,
  sym_number = 42,
  sym_svalue = 43,
  sym_var = 44,
  sym_ref = 45,
  sym_ref_for = 46,
  sym_inline_arithmetic = 47,
  sym_inline_arithmetic2 = 48,
  aux_sym__list_repeat1 = 49,
  aux_sym_svalue_repeat1 = 50,
  aux_sym_ref_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUND_LBRACK] = "#[",
  [aux_sym_annotation_token1] = "annotation_token1",
  [anon_sym_RBRACK] = "]",
  [sym_comment] = "comment",
  [anon_sym_] = " ",
  [anon_sym_LF] = "\n",
  [anon_sym_CR] = "\r",
  [anon_sym_TAB] = "\t",
  [anon_sym_LBRACE_RBRACE] = "{}",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK_LBRACK] = "[[",
  [anon_sym_EQ] = "=",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_LT] = "<",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_GT] = ">",
  [sym_digits] = "digits",
  [aux_sym_number_token1] = "number_token1",
  [sym_identifier] = "identifier",
  [anon_sym_value_COLON] = "value:",
  [anon_sym_PIPE] = "|",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_AT] = "@",
  [anon_sym_COLON] = ":",
  [sym_quoted] = "quoted",
  [anon_sym_AT_LBRACK] = "@[",
  [aux_sym_inline_arithmetic_token1] = "inline_arithmetic_token1",
  [anon_sym_AT_BSLASH_LBRACK] = "@\\[",
  [sym_source_file] = "source_file",
  [aux_sym__ws] = "_ws",
  [sym__list] = "_list",
  [sym__list_item] = "_list_item",
  [sym_list] = "list",
  [sym_if_list] = "if_list",
  [sym_statement] = "statement",
  [sym_operator] = "operator",
  [sym__bvalue] = "_bvalue",
  [sym__lvalue] = "_lvalue",
  [sym__rvalue] = "_rvalue",
  [sym_number] = "number",
  [sym_svalue] = "svalue",
  [sym_var] = "var",
  [sym_ref] = "ref",
  [sym_ref_for] = "ref_for",
  [sym_inline_arithmetic] = "inline_arithmetic",
  [sym_inline_arithmetic2] = "inline_arithmetic2",
  [aux_sym__list_repeat1] = "_list_repeat1",
  [aux_sym_svalue_repeat1] = "svalue_repeat1",
  [aux_sym_ref_repeat1] = "ref_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUND_LBRACK] = anon_sym_POUND_LBRACK,
  [aux_sym_annotation_token1] = aux_sym_annotation_token1,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_comment] = sym_comment,
  [anon_sym_] = anon_sym_,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_CR] = anon_sym_CR,
  [anon_sym_TAB] = anon_sym_TAB,
  [anon_sym_LBRACE_RBRACE] = anon_sym_LBRACE_RBRACE,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK_LBRACK] = anon_sym_LBRACK_LBRACK,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [sym_digits] = sym_digits,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [sym_identifier] = sym_identifier,
  [anon_sym_value_COLON] = anon_sym_value_COLON,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_quoted] = sym_quoted,
  [anon_sym_AT_LBRACK] = anon_sym_AT_LBRACK,
  [aux_sym_inline_arithmetic_token1] = aux_sym_inline_arithmetic_token1,
  [anon_sym_AT_BSLASH_LBRACK] = anon_sym_AT_BSLASH_LBRACK,
  [sym_source_file] = sym_source_file,
  [aux_sym__ws] = aux_sym__ws,
  [sym__list] = sym__list,
  [sym__list_item] = sym__list_item,
  [sym_list] = sym_list,
  [sym_if_list] = sym_if_list,
  [sym_statement] = sym_statement,
  [sym_operator] = sym_operator,
  [sym__bvalue] = sym__bvalue,
  [sym__lvalue] = sym__lvalue,
  [sym__rvalue] = sym__rvalue,
  [sym_number] = sym_number,
  [sym_svalue] = sym_svalue,
  [sym_var] = sym_var,
  [sym_ref] = sym_ref,
  [sym_ref_for] = sym_ref_for,
  [sym_inline_arithmetic] = sym_inline_arithmetic,
  [sym_inline_arithmetic2] = sym_inline_arithmetic2,
  [aux_sym__list_repeat1] = aux_sym__list_repeat1,
  [aux_sym_svalue_repeat1] = aux_sym_svalue_repeat1,
  [aux_sym_ref_repeat1] = aux_sym_ref_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_annotation_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TAB] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_digits] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_value_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_quoted] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_inline_arithmetic_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_AT_BSLASH_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__ws] = {
    .visible = false,
    .named = false,
  },
  [sym__list] = {
    .visible = false,
    .named = true,
  },
  [sym__list_item] = {
    .visible = false,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_if_list] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym__bvalue] = {
    .visible = false,
    .named = true,
  },
  [sym__lvalue] = {
    .visible = false,
    .named = true,
  },
  [sym__rvalue] = {
    .visible = false,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_svalue] = {
    .visible = true,
    .named = true,
  },
  [sym_var] = {
    .visible = true,
    .named = true,
  },
  [sym_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_for] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_arithmetic] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_arithmetic2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_svalue_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ref_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_for = 1,
  field_left = 2,
  field_macro = 3,
  field_name = 4,
  field_op = 5,
  field_prefix = 6,
  field_right = 7,
  field_value = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_for] = "for",
  [field_left] = "left",
  [field_macro] = "macro",
  [field_name] = "name",
  [field_op] = "op",
  [field_prefix] = "prefix",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 3},
  [7] = {.index = 10, .length = 2},
  [8] = {.index = 12, .length = 3},
  [9] = {.index = 15, .length = 3},
  [10] = {.index = 18, .length = 1},
  [11] = {.index = 19, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_prefix, 0},
  [2] =
    {field_value, 1},
  [3] =
    {field_name, 1},
    {field_prefix, 0, .inherited = true},
  [5] =
    {field_prefix, 0, .inherited = true},
    {field_prefix, 1, .inherited = true},
  [7] =
    {field_left, 0},
    {field_op, 1},
    {field_right, 2},
  [10] =
    {field_for, 2},
    {field_name, 0},
  [12] =
    {field_left, 0},
    {field_op, 2},
    {field_right, 3},
  [15] =
    {field_left, 0},
    {field_op, 1},
    {field_right, 3},
  [18] =
    {field_macro, 1},
  [19] =
    {field_left, 0},
    {field_op, 2},
    {field_right, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 2,
  [10] = 3,
  [11] = 6,
  [12] = 4,
  [13] = 5,
  [14] = 14,
  [15] = 14,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 16,
  [20] = 17,
  [21] = 21,
  [22] = 18,
  [23] = 21,
  [24] = 24,
  [25] = 24,
  [26] = 26,
  [27] = 27,
  [28] = 27,
  [29] = 26,
  [30] = 30,
  [31] = 31,
  [32] = 31,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 33,
  [37] = 37,
  [38] = 34,
  [39] = 39,
  [40] = 37,
  [41] = 35,
  [42] = 42,
  [43] = 39,
  [44] = 42,
  [45] = 45,
  [46] = 45,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 52,
  [54] = 48,
  [55] = 55,
  [56] = 56,
  [57] = 49,
  [58] = 51,
  [59] = 59,
  [60] = 50,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 59,
  [67] = 67,
  [68] = 55,
  [69] = 56,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 72,
  [75] = 73,
  [76] = 62,
  [77] = 70,
  [78] = 63,
  [79] = 61,
  [80] = 65,
  [81] = 71,
  [82] = 67,
  [83] = 64,
  [84] = 84,
  [85] = 84,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 88,
  [90] = 87,
  [91] = 91,
  [92] = 92,
  [93] = 91,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 98,
  [106] = 97,
  [107] = 107,
  [108] = 108,
  [109] = 100,
  [110] = 110,
  [111] = 107,
  [112] = 110,
  [113] = 104,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 96,
  [118] = 95,
  [119] = 119,
  [120] = 120,
  [121] = 114,
  [122] = 108,
  [123] = 119,
  [124] = 101,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      if (lookahead == '\t') ADVANCE(26);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\r') ADVANCE(25);
      if (lookahead == ' ') ADVANCE(23);
      if (lookahead == '!') ADVANCE(3);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '#') ADVANCE(4);
      if (lookahead == '$') ADVANCE(51);
      if (lookahead == ':') ADVANCE(54);
      if (lookahead == '<') ADVANCE(34);
      if (lookahead == '=') ADVANCE(31);
      if (lookahead == '>') ADVANCE(36);
      if (lookahead == '@') ADVANCE(53);
      if (lookahead == '[') ADVANCE(5);
      if (lookahead == ']') ADVANCE(21);
      if (lookahead == 'v') ADVANCE(16);
      if (lookahead == '{') ADVANCE(28);
      if (lookahead == '|') ADVANCE(50);
      if (lookahead == '}') ADVANCE(29);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '+') ADVANCE(7);
      if (lookahead == '-') ADVANCE(46);
      if (lookahead == '@') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (lookahead == '$' ||
          lookahead == '\'' ||
          lookahead == '.' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(48);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(55);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 4:
      if (lookahead == '[') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == '[') ADVANCE(30);
      END_STATE();
    case 6:
      if (lookahead == '[') ADVANCE(58);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 9:
      if (eof) ADVANCE(12);
      if (lookahead == '\t') ADVANCE(26);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\r') ADVANCE(25);
      if (lookahead == ' ') ADVANCE(23);
      if (lookahead == '!') ADVANCE(3);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == '+') ADVANCE(7);
      if (lookahead == '-') ADVANCE(46);
      if (lookahead == ':') ADVANCE(54);
      if (lookahead == '<') ADVANCE(34);
      if (lookahead == '=') ADVANCE(31);
      if (lookahead == '>') ADVANCE(36);
      if (lookahead == '@') ADVANCE(53);
      if (lookahead == '[') ADVANCE(5);
      if (lookahead == ']') ADVANCE(21);
      if (lookahead == 'v') ADVANCE(42);
      if (lookahead == '{') ADVANCE(28);
      if (lookahead == '}') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (lookahead == '$' ||
          lookahead == '\'' ||
          lookahead == '.' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '|')) ADVANCE(48);
      END_STATE();
    case 10:
      if (eof) ADVANCE(12);
      if (lookahead == '\t') ADVANCE(26);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\r') ADVANCE(25);
      if (lookahead == ' ') ADVANCE(23);
      if (lookahead == '!') ADVANCE(3);
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == ':') ADVANCE(54);
      if (lookahead == '<') ADVANCE(34);
      if (lookahead == '=') ADVANCE(31);
      if (lookahead == '>') ADVANCE(36);
      if (lookahead == '@') ADVANCE(52);
      if (lookahead == ']') ADVANCE(21);
      if (lookahead == '|') ADVANCE(50);
      if (lookahead == '}') ADVANCE(29);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == '\t') ADVANCE(26);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\r') ADVANCE(25);
      if (lookahead == ' ') ADVANCE(23);
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == ']') ADVANCE(21);
      if (lookahead == '}') ADVANCE(29);
      if (lookahead == '$' ||
          lookahead == '\'' ||
          ('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(48);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_POUND_LBRACK);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_annotation_token1);
      if (lookahead == '.') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_annotation_token1);
      if (lookahead == ':') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_annotation_token1);
      if (lookahead == 'a') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_annotation_token1);
      if (lookahead == 'e') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_annotation_token1);
      if (lookahead == 'l') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_annotation_token1);
      if (lookahead == 'u') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_annotation_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_CR);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_TAB);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACE_RBRACE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '}') ADVANCE(27);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LBRACK_LBRACK);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(33);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(35);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (lookahead == '$' ||
          lookahead == '\'' ||
          ('-' <= lookahead && lookahead <= '/') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(48);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (lookahead == '$' ||
          lookahead == '\'' ||
          ('-' <= lookahead && lookahead <= '/') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(48);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead == '$' ||
          lookahead == '\'' ||
          ('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(48);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(44);
      if (lookahead == '$' ||
          lookahead == '\'' ||
          ('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(48);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(41);
      if (lookahead == '$' ||
          lookahead == '\'' ||
          ('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(48);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(45);
      if (lookahead == '$' ||
          lookahead == '\'' ||
          ('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(48);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(43);
      if (lookahead == '$' ||
          lookahead == '\'' ||
          ('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(48);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (lookahead == '$' ||
          lookahead == '\'' ||
          ('-' <= lookahead && lookahead <= '/') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(48);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (lookahead == '$' ||
          lookahead == '\'' ||
          ('-' <= lookahead && lookahead <= '/') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(48);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '$' ||
          lookahead == '\'' ||
          ('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_value_COLON);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead == '[') ADVANCE(56);
      if (lookahead == '\\') ADVANCE(6);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_quoted);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_AT_LBRACK);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_inline_arithmetic_token1);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_AT_BSLASH_LBRACK);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 9},
  [2] = {.lex_state = 9},
  [3] = {.lex_state = 9},
  [4] = {.lex_state = 9},
  [5] = {.lex_state = 9},
  [6] = {.lex_state = 9},
  [7] = {.lex_state = 9},
  [8] = {.lex_state = 9},
  [9] = {.lex_state = 9},
  [10] = {.lex_state = 9},
  [11] = {.lex_state = 9},
  [12] = {.lex_state = 9},
  [13] = {.lex_state = 9},
  [14] = {.lex_state = 9},
  [15] = {.lex_state = 9},
  [16] = {.lex_state = 9},
  [17] = {.lex_state = 9},
  [18] = {.lex_state = 9},
  [19] = {.lex_state = 9},
  [20] = {.lex_state = 9},
  [21] = {.lex_state = 9},
  [22] = {.lex_state = 9},
  [23] = {.lex_state = 9},
  [24] = {.lex_state = 9},
  [25] = {.lex_state = 9},
  [26] = {.lex_state = 9},
  [27] = {.lex_state = 9},
  [28] = {.lex_state = 10},
  [29] = {.lex_state = 10},
  [30] = {.lex_state = 9},
  [31] = {.lex_state = 10},
  [32] = {.lex_state = 9},
  [33] = {.lex_state = 9},
  [34] = {.lex_state = 10},
  [35] = {.lex_state = 9},
  [36] = {.lex_state = 10},
  [37] = {.lex_state = 9},
  [38] = {.lex_state = 9},
  [39] = {.lex_state = 10},
  [40] = {.lex_state = 9},
  [41] = {.lex_state = 9},
  [42] = {.lex_state = 9},
  [43] = {.lex_state = 9},
  [44] = {.lex_state = 9},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 9},
  [49] = {.lex_state = 9},
  [50] = {.lex_state = 9},
  [51] = {.lex_state = 9},
  [52] = {.lex_state = 9},
  [53] = {.lex_state = 9},
  [54] = {.lex_state = 9},
  [55] = {.lex_state = 10},
  [56] = {.lex_state = 11},
  [57] = {.lex_state = 9},
  [58] = {.lex_state = 9},
  [59] = {.lex_state = 11},
  [60] = {.lex_state = 9},
  [61] = {.lex_state = 9},
  [62] = {.lex_state = 9},
  [63] = {.lex_state = 9},
  [64] = {.lex_state = 9},
  [65] = {.lex_state = 9},
  [66] = {.lex_state = 11},
  [67] = {.lex_state = 9},
  [68] = {.lex_state = 10},
  [69] = {.lex_state = 11},
  [70] = {.lex_state = 9},
  [71] = {.lex_state = 9},
  [72] = {.lex_state = 9},
  [73] = {.lex_state = 9},
  [74] = {.lex_state = 9},
  [75] = {.lex_state = 9},
  [76] = {.lex_state = 9},
  [77] = {.lex_state = 9},
  [78] = {.lex_state = 9},
  [79] = {.lex_state = 9},
  [80] = {.lex_state = 9},
  [81] = {.lex_state = 9},
  [82] = {.lex_state = 9},
  [83] = {.lex_state = 9},
  [84] = {.lex_state = 11},
  [85] = {.lex_state = 11},
  [86] = {.lex_state = 11},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 11},
  [89] = {.lex_state = 11},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 57},
  [96] = {.lex_state = 57},
  [97] = {.lex_state = 11},
  [98] = {.lex_state = 11},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 11},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 11},
  [106] = {.lex_state = 11},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 11},
  [117] = {.lex_state = 57},
  [118] = {.lex_state = 57},
  [119] = {.lex_state = 11},
  [120] = {.lex_state = 11},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 11},
  [124] = {.lex_state = 11},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND_LBRACK] = ACTIONS(1),
    [aux_sym_annotation_token1] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_CR] = ACTIONS(1),
    [anon_sym_TAB] = ACTIONS(1),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym_digits] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [anon_sym_value_COLON] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_quoted] = ACTIONS(1),
    [anon_sym_AT_LBRACK] = ACTIONS(1),
    [anon_sym_AT_BSLASH_LBRACK] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(94),
    [aux_sym__ws] = STATE(13),
    [sym__list] = STATE(102),
    [sym__list_item] = STATE(58),
    [sym_list] = STATE(58),
    [sym_if_list] = STATE(58),
    [sym_statement] = STATE(58),
    [sym__bvalue] = STATE(44),
    [sym__lvalue] = STATE(40),
    [sym__rvalue] = STATE(58),
    [sym_number] = STATE(44),
    [sym_svalue] = STATE(58),
    [sym_var] = STATE(44),
    [sym_ref] = STATE(31),
    [sym_ref_for] = STATE(44),
    [sym_inline_arithmetic] = STATE(58),
    [sym_inline_arithmetic2] = STATE(58),
    [aux_sym_ref_repeat1] = STATE(89),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [anon_sym_] = ACTIONS(5),
    [anon_sym_LF] = ACTIONS(5),
    [anon_sym_CR] = ACTIONS(5),
    [anon_sym_TAB] = ACTIONS(5),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(11),
    [aux_sym_number_token1] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [anon_sym_value_COLON] = ACTIONS(17),
    [anon_sym_AT] = ACTIONS(19),
    [sym_quoted] = ACTIONS(21),
    [anon_sym_AT_LBRACK] = ACTIONS(23),
    [anon_sym_AT_BSLASH_LBRACK] = ACTIONS(25),
  },
  [2] = {
    [aux_sym__ws] = STATE(24),
    [sym__list_item] = STATE(71),
    [sym_list] = STATE(71),
    [sym_if_list] = STATE(71),
    [sym_statement] = STATE(71),
    [sym__bvalue] = STATE(42),
    [sym__lvalue] = STATE(37),
    [sym__rvalue] = STATE(71),
    [sym_number] = STATE(42),
    [sym_svalue] = STATE(71),
    [sym_var] = STATE(42),
    [sym_ref] = STATE(32),
    [sym_ref_for] = STATE(42),
    [sym_inline_arithmetic] = STATE(71),
    [sym_inline_arithmetic2] = STATE(71),
    [aux_sym_ref_repeat1] = STATE(88),
    [anon_sym_RBRACK] = ACTIONS(27),
    [sym_comment] = ACTIONS(29),
    [anon_sym_] = ACTIONS(29),
    [anon_sym_LF] = ACTIONS(29),
    [anon_sym_CR] = ACTIONS(29),
    [anon_sym_TAB] = ACTIONS(29),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_RBRACE] = ACTIONS(27),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(35),
    [aux_sym_number_token1] = ACTIONS(37),
    [sym_identifier] = ACTIONS(39),
    [anon_sym_value_COLON] = ACTIONS(41),
    [anon_sym_AT] = ACTIONS(43),
    [sym_quoted] = ACTIONS(45),
    [anon_sym_AT_LBRACK] = ACTIONS(47),
    [anon_sym_AT_BSLASH_LBRACK] = ACTIONS(49),
  },
  [3] = {
    [aux_sym__ws] = STATE(24),
    [sym__list_item] = STATE(71),
    [sym_list] = STATE(71),
    [sym_if_list] = STATE(71),
    [sym_statement] = STATE(71),
    [sym__bvalue] = STATE(42),
    [sym__lvalue] = STATE(37),
    [sym__rvalue] = STATE(71),
    [sym_number] = STATE(42),
    [sym_svalue] = STATE(71),
    [sym_var] = STATE(42),
    [sym_ref] = STATE(32),
    [sym_ref_for] = STATE(42),
    [sym_inline_arithmetic] = STATE(71),
    [sym_inline_arithmetic2] = STATE(71),
    [aux_sym_ref_repeat1] = STATE(88),
    [anon_sym_RBRACK] = ACTIONS(51),
    [sym_comment] = ACTIONS(29),
    [anon_sym_] = ACTIONS(29),
    [anon_sym_LF] = ACTIONS(29),
    [anon_sym_CR] = ACTIONS(29),
    [anon_sym_TAB] = ACTIONS(29),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_RBRACE] = ACTIONS(51),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(35),
    [aux_sym_number_token1] = ACTIONS(37),
    [sym_identifier] = ACTIONS(39),
    [anon_sym_value_COLON] = ACTIONS(41),
    [anon_sym_AT] = ACTIONS(43),
    [sym_quoted] = ACTIONS(45),
    [anon_sym_AT_LBRACK] = ACTIONS(47),
    [anon_sym_AT_BSLASH_LBRACK] = ACTIONS(49),
  },
  [4] = {
    [aux_sym__ws] = STATE(24),
    [sym__list_item] = STATE(71),
    [sym_list] = STATE(71),
    [sym_if_list] = STATE(71),
    [sym_statement] = STATE(71),
    [sym__bvalue] = STATE(42),
    [sym__lvalue] = STATE(37),
    [sym__rvalue] = STATE(71),
    [sym_number] = STATE(42),
    [sym_svalue] = STATE(71),
    [sym_var] = STATE(42),
    [sym_ref] = STATE(32),
    [sym_ref_for] = STATE(42),
    [sym_inline_arithmetic] = STATE(71),
    [sym_inline_arithmetic2] = STATE(71),
    [aux_sym_ref_repeat1] = STATE(88),
    [anon_sym_RBRACK] = ACTIONS(53),
    [sym_comment] = ACTIONS(29),
    [anon_sym_] = ACTIONS(29),
    [anon_sym_LF] = ACTIONS(29),
    [anon_sym_CR] = ACTIONS(29),
    [anon_sym_TAB] = ACTIONS(29),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_RBRACE] = ACTIONS(53),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(35),
    [aux_sym_number_token1] = ACTIONS(37),
    [sym_identifier] = ACTIONS(39),
    [anon_sym_value_COLON] = ACTIONS(41),
    [anon_sym_AT] = ACTIONS(43),
    [sym_quoted] = ACTIONS(45),
    [anon_sym_AT_LBRACK] = ACTIONS(47),
    [anon_sym_AT_BSLASH_LBRACK] = ACTIONS(49),
  },
  [5] = {
    [aux_sym__ws] = STATE(24),
    [sym__list_item] = STATE(52),
    [sym_list] = STATE(52),
    [sym_if_list] = STATE(52),
    [sym_statement] = STATE(52),
    [sym__bvalue] = STATE(42),
    [sym__lvalue] = STATE(37),
    [sym__rvalue] = STATE(52),
    [sym_number] = STATE(42),
    [sym_svalue] = STATE(52),
    [sym_var] = STATE(42),
    [sym_ref] = STATE(32),
    [sym_ref_for] = STATE(42),
    [sym_inline_arithmetic] = STATE(52),
    [sym_inline_arithmetic2] = STATE(52),
    [aux_sym_ref_repeat1] = STATE(88),
    [anon_sym_RBRACK] = ACTIONS(55),
    [sym_comment] = ACTIONS(29),
    [anon_sym_] = ACTIONS(29),
    [anon_sym_LF] = ACTIONS(29),
    [anon_sym_CR] = ACTIONS(29),
    [anon_sym_TAB] = ACTIONS(29),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_RBRACE] = ACTIONS(55),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(35),
    [aux_sym_number_token1] = ACTIONS(37),
    [sym_identifier] = ACTIONS(39),
    [anon_sym_value_COLON] = ACTIONS(41),
    [anon_sym_AT] = ACTIONS(43),
    [sym_quoted] = ACTIONS(45),
    [anon_sym_AT_LBRACK] = ACTIONS(47),
    [anon_sym_AT_BSLASH_LBRACK] = ACTIONS(49),
  },
  [6] = {
    [aux_sym__ws] = STATE(5),
    [sym__list] = STATE(113),
    [sym__list_item] = STATE(51),
    [sym_list] = STATE(51),
    [sym_if_list] = STATE(51),
    [sym_statement] = STATE(51),
    [sym__bvalue] = STATE(42),
    [sym__lvalue] = STATE(37),
    [sym__rvalue] = STATE(51),
    [sym_number] = STATE(42),
    [sym_svalue] = STATE(51),
    [sym_var] = STATE(42),
    [sym_ref] = STATE(32),
    [sym_ref_for] = STATE(42),
    [sym_inline_arithmetic] = STATE(51),
    [sym_inline_arithmetic2] = STATE(51),
    [aux_sym_ref_repeat1] = STATE(88),
    [sym_comment] = ACTIONS(57),
    [anon_sym_] = ACTIONS(57),
    [anon_sym_LF] = ACTIONS(57),
    [anon_sym_CR] = ACTIONS(57),
    [anon_sym_TAB] = ACTIONS(57),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(35),
    [aux_sym_number_token1] = ACTIONS(37),
    [sym_identifier] = ACTIONS(39),
    [anon_sym_value_COLON] = ACTIONS(41),
    [anon_sym_AT] = ACTIONS(43),
    [sym_quoted] = ACTIONS(45),
    [anon_sym_AT_LBRACK] = ACTIONS(47),
    [anon_sym_AT_BSLASH_LBRACK] = ACTIONS(49),
  },
  [7] = {
    [aux_sym__ws] = STATE(5),
    [sym__list] = STATE(100),
    [sym__list_item] = STATE(51),
    [sym_list] = STATE(51),
    [sym_if_list] = STATE(51),
    [sym_statement] = STATE(51),
    [sym__bvalue] = STATE(42),
    [sym__lvalue] = STATE(37),
    [sym__rvalue] = STATE(51),
    [sym_number] = STATE(42),
    [sym_svalue] = STATE(51),
    [sym_var] = STATE(42),
    [sym_ref] = STATE(32),
    [sym_ref_for] = STATE(42),
    [sym_inline_arithmetic] = STATE(51),
    [sym_inline_arithmetic2] = STATE(51),
    [aux_sym_ref_repeat1] = STATE(88),
    [sym_comment] = ACTIONS(57),
    [anon_sym_] = ACTIONS(57),
    [anon_sym_LF] = ACTIONS(57),
    [anon_sym_CR] = ACTIONS(57),
    [anon_sym_TAB] = ACTIONS(57),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(35),
    [aux_sym_number_token1] = ACTIONS(37),
    [sym_identifier] = ACTIONS(39),
    [anon_sym_value_COLON] = ACTIONS(41),
    [anon_sym_AT] = ACTIONS(43),
    [sym_quoted] = ACTIONS(45),
    [anon_sym_AT_LBRACK] = ACTIONS(47),
    [anon_sym_AT_BSLASH_LBRACK] = ACTIONS(49),
  },
  [8] = {
    [aux_sym__ws] = STATE(5),
    [sym__list] = STATE(109),
    [sym__list_item] = STATE(51),
    [sym_list] = STATE(51),
    [sym_if_list] = STATE(51),
    [sym_statement] = STATE(51),
    [sym__bvalue] = STATE(42),
    [sym__lvalue] = STATE(37),
    [sym__rvalue] = STATE(51),
    [sym_number] = STATE(42),
    [sym_svalue] = STATE(51),
    [sym_var] = STATE(42),
    [sym_ref] = STATE(32),
    [sym_ref_for] = STATE(42),
    [sym_inline_arithmetic] = STATE(51),
    [sym_inline_arithmetic2] = STATE(51),
    [aux_sym_ref_repeat1] = STATE(88),
    [sym_comment] = ACTIONS(57),
    [anon_sym_] = ACTIONS(57),
    [anon_sym_LF] = ACTIONS(57),
    [anon_sym_CR] = ACTIONS(57),
    [anon_sym_TAB] = ACTIONS(57),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(35),
    [aux_sym_number_token1] = ACTIONS(37),
    [sym_identifier] = ACTIONS(39),
    [anon_sym_value_COLON] = ACTIONS(41),
    [anon_sym_AT] = ACTIONS(43),
    [sym_quoted] = ACTIONS(45),
    [anon_sym_AT_LBRACK] = ACTIONS(47),
    [anon_sym_AT_BSLASH_LBRACK] = ACTIONS(49),
  },
  [9] = {
    [aux_sym__ws] = STATE(25),
    [sym__list_item] = STATE(81),
    [sym_list] = STATE(81),
    [sym_if_list] = STATE(81),
    [sym_statement] = STATE(81),
    [sym__bvalue] = STATE(44),
    [sym__lvalue] = STATE(40),
    [sym__rvalue] = STATE(81),
    [sym_number] = STATE(44),
    [sym_svalue] = STATE(81),
    [sym_var] = STATE(44),
    [sym_ref] = STATE(31),
    [sym_ref_for] = STATE(44),
    [sym_inline_arithmetic] = STATE(81),
    [sym_inline_arithmetic2] = STATE(81),
    [aux_sym_ref_repeat1] = STATE(89),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_comment] = ACTIONS(59),
    [anon_sym_] = ACTIONS(59),
    [anon_sym_LF] = ACTIONS(59),
    [anon_sym_CR] = ACTIONS(59),
    [anon_sym_TAB] = ACTIONS(59),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(11),
    [aux_sym_number_token1] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [anon_sym_value_COLON] = ACTIONS(17),
    [anon_sym_AT] = ACTIONS(19),
    [sym_quoted] = ACTIONS(21),
    [anon_sym_AT_LBRACK] = ACTIONS(23),
    [anon_sym_AT_BSLASH_LBRACK] = ACTIONS(25),
  },
  [10] = {
    [aux_sym__ws] = STATE(25),
    [sym__list_item] = STATE(81),
    [sym_list] = STATE(81),
    [sym_if_list] = STATE(81),
    [sym_statement] = STATE(81),
    [sym__bvalue] = STATE(44),
    [sym__lvalue] = STATE(40),
    [sym__rvalue] = STATE(81),
    [sym_number] = STATE(44),
    [sym_svalue] = STATE(81),
    [sym_var] = STATE(44),
    [sym_ref] = STATE(31),
    [sym_ref_for] = STATE(44),
    [sym_inline_arithmetic] = STATE(81),
    [sym_inline_arithmetic2] = STATE(81),
    [aux_sym_ref_repeat1] = STATE(89),
    [ts_builtin_sym_end] = ACTIONS(51),
    [sym_comment] = ACTIONS(59),
    [anon_sym_] = ACTIONS(59),
    [anon_sym_LF] = ACTIONS(59),
    [anon_sym_CR] = ACTIONS(59),
    [anon_sym_TAB] = ACTIONS(59),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(11),
    [aux_sym_number_token1] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [anon_sym_value_COLON] = ACTIONS(17),
    [anon_sym_AT] = ACTIONS(19),
    [sym_quoted] = ACTIONS(21),
    [anon_sym_AT_LBRACK] = ACTIONS(23),
    [anon_sym_AT_BSLASH_LBRACK] = ACTIONS(25),
  },
  [11] = {
    [aux_sym__ws] = STATE(5),
    [sym__list] = STATE(104),
    [sym__list_item] = STATE(51),
    [sym_list] = STATE(51),
    [sym_if_list] = STATE(51),
    [sym_statement] = STATE(51),
    [sym__bvalue] = STATE(42),
    [sym__lvalue] = STATE(37),
    [sym__rvalue] = STATE(51),
    [sym_number] = STATE(42),
    [sym_svalue] = STATE(51),
    [sym_var] = STATE(42),
    [sym_ref] = STATE(32),
    [sym_ref_for] = STATE(42),
    [sym_inline_arithmetic] = STATE(51),
    [sym_inline_arithmetic2] = STATE(51),
    [aux_sym_ref_repeat1] = STATE(88),
    [sym_comment] = ACTIONS(57),
    [anon_sym_] = ACTIONS(57),
    [anon_sym_LF] = ACTIONS(57),
    [anon_sym_CR] = ACTIONS(57),
    [anon_sym_TAB] = ACTIONS(57),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(35),
    [aux_sym_number_token1] = ACTIONS(37),
    [sym_identifier] = ACTIONS(39),
    [anon_sym_value_COLON] = ACTIONS(41),
    [anon_sym_AT] = ACTIONS(43),
    [sym_quoted] = ACTIONS(45),
    [anon_sym_AT_LBRACK] = ACTIONS(47),
    [anon_sym_AT_BSLASH_LBRACK] = ACTIONS(49),
  },
  [12] = {
    [aux_sym__ws] = STATE(25),
    [sym__list_item] = STATE(81),
    [sym_list] = STATE(81),
    [sym_if_list] = STATE(81),
    [sym_statement] = STATE(81),
    [sym__bvalue] = STATE(44),
    [sym__lvalue] = STATE(40),
    [sym__rvalue] = STATE(81),
    [sym_number] = STATE(44),
    [sym_svalue] = STATE(81),
    [sym_var] = STATE(44),
    [sym_ref] = STATE(31),
    [sym_ref_for] = STATE(44),
    [sym_inline_arithmetic] = STATE(81),
    [sym_inline_arithmetic2] = STATE(81),
    [aux_sym_ref_repeat1] = STATE(89),
    [ts_builtin_sym_end] = ACTIONS(53),
    [sym_comment] = ACTIONS(59),
    [anon_sym_] = ACTIONS(59),
    [anon_sym_LF] = ACTIONS(59),
    [anon_sym_CR] = ACTIONS(59),
    [anon_sym_TAB] = ACTIONS(59),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(11),
    [aux_sym_number_token1] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [anon_sym_value_COLON] = ACTIONS(17),
    [anon_sym_AT] = ACTIONS(19),
    [sym_quoted] = ACTIONS(21),
    [anon_sym_AT_LBRACK] = ACTIONS(23),
    [anon_sym_AT_BSLASH_LBRACK] = ACTIONS(25),
  },
  [13] = {
    [aux_sym__ws] = STATE(25),
    [sym__list_item] = STATE(53),
    [sym_list] = STATE(53),
    [sym_if_list] = STATE(53),
    [sym_statement] = STATE(53),
    [sym__bvalue] = STATE(44),
    [sym__lvalue] = STATE(40),
    [sym__rvalue] = STATE(53),
    [sym_number] = STATE(44),
    [sym_svalue] = STATE(53),
    [sym_var] = STATE(44),
    [sym_ref] = STATE(31),
    [sym_ref_for] = STATE(44),
    [sym_inline_arithmetic] = STATE(53),
    [sym_inline_arithmetic2] = STATE(53),
    [aux_sym_ref_repeat1] = STATE(89),
    [ts_builtin_sym_end] = ACTIONS(55),
    [sym_comment] = ACTIONS(59),
    [anon_sym_] = ACTIONS(59),
    [anon_sym_LF] = ACTIONS(59),
    [anon_sym_CR] = ACTIONS(59),
    [anon_sym_TAB] = ACTIONS(59),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(11),
    [aux_sym_number_token1] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [anon_sym_value_COLON] = ACTIONS(17),
    [anon_sym_AT] = ACTIONS(19),
    [sym_quoted] = ACTIONS(21),
    [anon_sym_AT_LBRACK] = ACTIONS(23),
    [anon_sym_AT_BSLASH_LBRACK] = ACTIONS(25),
  },
  [14] = {
    [aux_sym__ws] = STATE(24),
    [sym__list_item] = STATE(71),
    [sym_list] = STATE(71),
    [sym_if_list] = STATE(71),
    [sym_statement] = STATE(71),
    [sym__bvalue] = STATE(42),
    [sym__lvalue] = STATE(37),
    [sym__rvalue] = STATE(71),
    [sym_number] = STATE(42),
    [sym_svalue] = STATE(71),
    [sym_var] = STATE(42),
    [sym_ref] = STATE(32),
    [sym_ref_for] = STATE(42),
    [sym_inline_arithmetic] = STATE(71),
    [sym_inline_arithmetic2] = STATE(71),
    [aux_sym_ref_repeat1] = STATE(88),
    [sym_comment] = ACTIONS(29),
    [anon_sym_] = ACTIONS(29),
    [anon_sym_LF] = ACTIONS(29),
    [anon_sym_CR] = ACTIONS(29),
    [anon_sym_TAB] = ACTIONS(29),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(35),
    [aux_sym_number_token1] = ACTIONS(37),
    [sym_identifier] = ACTIONS(39),
    [anon_sym_value_COLON] = ACTIONS(41),
    [anon_sym_AT] = ACTIONS(43),
    [sym_quoted] = ACTIONS(45),
    [anon_sym_AT_LBRACK] = ACTIONS(47),
    [anon_sym_AT_BSLASH_LBRACK] = ACTIONS(49),
  },
  [15] = {
    [aux_sym__ws] = STATE(24),
    [sym__list_item] = STATE(81),
    [sym_list] = STATE(81),
    [sym_if_list] = STATE(81),
    [sym_statement] = STATE(81),
    [sym__bvalue] = STATE(44),
    [sym__lvalue] = STATE(40),
    [sym__rvalue] = STATE(81),
    [sym_number] = STATE(44),
    [sym_svalue] = STATE(81),
    [sym_var] = STATE(44),
    [sym_ref] = STATE(31),
    [sym_ref_for] = STATE(44),
    [sym_inline_arithmetic] = STATE(81),
    [sym_inline_arithmetic2] = STATE(81),
    [aux_sym_ref_repeat1] = STATE(89),
    [sym_comment] = ACTIONS(29),
    [anon_sym_] = ACTIONS(29),
    [anon_sym_LF] = ACTIONS(29),
    [anon_sym_CR] = ACTIONS(29),
    [anon_sym_TAB] = ACTIONS(29),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(11),
    [aux_sym_number_token1] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [anon_sym_value_COLON] = ACTIONS(17),
    [anon_sym_AT] = ACTIONS(19),
    [sym_quoted] = ACTIONS(21),
    [anon_sym_AT_LBRACK] = ACTIONS(23),
    [anon_sym_AT_BSLASH_LBRACK] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(31), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(33), 1,
      anon_sym_LBRACE,
    ACTIONS(37), 1,
      aux_sym_number_token1,
    ACTIONS(39), 1,
      sym_identifier,
    ACTIONS(41), 1,
      anon_sym_value_COLON,
    ACTIONS(43), 1,
      anon_sym_AT,
    ACTIONS(47), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(49), 1,
      anon_sym_AT_BSLASH_LBRACK,
    ACTIONS(63), 1,
      sym_quoted,
    STATE(22), 1,
      aux_sym__ws,
    STATE(32), 1,
      sym_ref,
    STATE(88), 1,
      aux_sym_ref_repeat1,
    ACTIONS(61), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
    STATE(65), 9,
      sym_list,
      sym__bvalue,
      sym__rvalue,
      sym_number,
      sym_svalue,
      sym_var,
      sym_ref_for,
      sym_inline_arithmetic,
      sym_inline_arithmetic2,
  [55] = 14,
    ACTIONS(31), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(33), 1,
      anon_sym_LBRACE,
    ACTIONS(37), 1,
      aux_sym_number_token1,
    ACTIONS(39), 1,
      sym_identifier,
    ACTIONS(41), 1,
      anon_sym_value_COLON,
    ACTIONS(43), 1,
      anon_sym_AT,
    ACTIONS(47), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(49), 1,
      anon_sym_AT_BSLASH_LBRACK,
    ACTIONS(65), 1,
      sym_quoted,
    STATE(24), 1,
      aux_sym__ws,
    STATE(32), 1,
      sym_ref,
    STATE(88), 1,
      aux_sym_ref_repeat1,
    ACTIONS(29), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
    STATE(64), 9,
      sym_list,
      sym__bvalue,
      sym__rvalue,
      sym_number,
      sym_svalue,
      sym_var,
      sym_ref_for,
      sym_inline_arithmetic,
      sym_inline_arithmetic2,
  [110] = 14,
    ACTIONS(7), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      aux_sym_number_token1,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_value_COLON,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(25), 1,
      anon_sym_AT_BSLASH_LBRACK,
    ACTIONS(67), 1,
      sym_quoted,
    STATE(24), 1,
      aux_sym__ws,
    STATE(31), 1,
      sym_ref,
    STATE(89), 1,
      aux_sym_ref_repeat1,
    ACTIONS(29), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
    STATE(79), 9,
      sym_list,
      sym__bvalue,
      sym__rvalue,
      sym_number,
      sym_svalue,
      sym_var,
      sym_ref_for,
      sym_inline_arithmetic,
      sym_inline_arithmetic2,
  [165] = 14,
    ACTIONS(7), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      aux_sym_number_token1,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_value_COLON,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(25), 1,
      anon_sym_AT_BSLASH_LBRACK,
    ACTIONS(71), 1,
      sym_quoted,
    STATE(18), 1,
      aux_sym__ws,
    STATE(31), 1,
      sym_ref,
    STATE(89), 1,
      aux_sym_ref_repeat1,
    ACTIONS(69), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
    STATE(80), 9,
      sym_list,
      sym__bvalue,
      sym__rvalue,
      sym_number,
      sym_svalue,
      sym_var,
      sym_ref_for,
      sym_inline_arithmetic,
      sym_inline_arithmetic2,
  [220] = 14,
    ACTIONS(7), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      aux_sym_number_token1,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_value_COLON,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(25), 1,
      anon_sym_AT_BSLASH_LBRACK,
    ACTIONS(73), 1,
      sym_quoted,
    STATE(24), 1,
      aux_sym__ws,
    STATE(31), 1,
      sym_ref,
    STATE(89), 1,
      aux_sym_ref_repeat1,
    ACTIONS(29), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
    STATE(83), 9,
      sym_list,
      sym__bvalue,
      sym__rvalue,
      sym_number,
      sym_svalue,
      sym_var,
      sym_ref_for,
      sym_inline_arithmetic,
      sym_inline_arithmetic2,
  [275] = 14,
    ACTIONS(31), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(33), 1,
      anon_sym_LBRACE,
    ACTIONS(37), 1,
      aux_sym_number_token1,
    ACTIONS(39), 1,
      sym_identifier,
    ACTIONS(41), 1,
      anon_sym_value_COLON,
    ACTIONS(43), 1,
      anon_sym_AT,
    ACTIONS(47), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(49), 1,
      anon_sym_AT_BSLASH_LBRACK,
    ACTIONS(77), 1,
      sym_quoted,
    STATE(17), 1,
      aux_sym__ws,
    STATE(32), 1,
      sym_ref,
    STATE(88), 1,
      aux_sym_ref_repeat1,
    ACTIONS(75), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
    STATE(70), 9,
      sym_list,
      sym__bvalue,
      sym__rvalue,
      sym_number,
      sym_svalue,
      sym_var,
      sym_ref_for,
      sym_inline_arithmetic,
      sym_inline_arithmetic2,
  [330] = 14,
    ACTIONS(31), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(33), 1,
      anon_sym_LBRACE,
    ACTIONS(37), 1,
      aux_sym_number_token1,
    ACTIONS(39), 1,
      sym_identifier,
    ACTIONS(41), 1,
      anon_sym_value_COLON,
    ACTIONS(43), 1,
      anon_sym_AT,
    ACTIONS(47), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(49), 1,
      anon_sym_AT_BSLASH_LBRACK,
    ACTIONS(79), 1,
      sym_quoted,
    STATE(24), 1,
      aux_sym__ws,
    STATE(32), 1,
      sym_ref,
    STATE(88), 1,
      aux_sym_ref_repeat1,
    ACTIONS(29), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
    STATE(61), 9,
      sym_list,
      sym__bvalue,
      sym__rvalue,
      sym_number,
      sym_svalue,
      sym_var,
      sym_ref_for,
      sym_inline_arithmetic,
      sym_inline_arithmetic2,
  [385] = 14,
    ACTIONS(7), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      aux_sym_number_token1,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_value_COLON,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_AT_LBRACK,
    ACTIONS(25), 1,
      anon_sym_AT_BSLASH_LBRACK,
    ACTIONS(83), 1,
      sym_quoted,
    STATE(20), 1,
      aux_sym__ws,
    STATE(31), 1,
      sym_ref,
    STATE(89), 1,
      aux_sym_ref_repeat1,
    ACTIONS(81), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
    STATE(77), 9,
      sym_list,
      sym__bvalue,
      sym__rvalue,
      sym_number,
      sym_svalue,
      sym_var,
      sym_ref_for,
      sym_inline_arithmetic,
      sym_inline_arithmetic2,
  [440] = 4,
    STATE(24), 1,
      aux_sym__ws,
    ACTIONS(87), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
    ACTIONS(90), 6,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_number_token1,
      sym_identifier,
      anon_sym_AT,
    ACTIONS(85), 12,
      anon_sym_RBRACK,
      anon_sym_LBRACE_RBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_value_COLON,
      sym_quoted,
      anon_sym_AT_LBRACK,
      anon_sym_AT_BSLASH_LBRACK,
  [473] = 4,
    STATE(25), 1,
      aux_sym__ws,
    ACTIONS(90), 4,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      sym_identifier,
      anon_sym_AT,
    ACTIONS(92), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
    ACTIONS(85), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_value_COLON,
      sym_quoted,
      anon_sym_AT_LBRACK,
      anon_sym_AT_BSLASH_LBRACK,
  [499] = 3,
    ACTIONS(99), 1,
      anon_sym_COLON,
    ACTIONS(97), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(95), 12,
      anon_sym_RBRACK,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AT,
  [521] = 3,
    ACTIONS(99), 1,
      anon_sym_COLON,
    ACTIONS(103), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(101), 12,
      anon_sym_RBRACK,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AT,
  [543] = 3,
    ACTIONS(99), 1,
      anon_sym_COLON,
    ACTIONS(103), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(101), 12,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE,
      anon_sym_AT,
  [565] = 3,
    ACTIONS(99), 1,
      anon_sym_COLON,
    ACTIONS(97), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(95), 12,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE,
      anon_sym_AT,
  [587] = 2,
    ACTIONS(107), 4,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      sym_identifier,
      anon_sym_AT,
    ACTIONS(105), 10,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_LBRACE_RBRACE,
      anon_sym_value_COLON,
      sym_quoted,
      anon_sym_AT_LBRACK,
      anon_sym_AT_BSLASH_LBRACK,
  [606] = 3,
    ACTIONS(113), 1,
      anon_sym_AT,
    ACTIONS(111), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(109), 11,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE,
  [627] = 3,
    ACTIONS(115), 1,
      anon_sym_AT,
    ACTIONS(111), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(109), 11,
      anon_sym_RBRACK,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [648] = 2,
    ACTIONS(119), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(117), 11,
      anon_sym_RBRACK,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [666] = 2,
    ACTIONS(123), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(121), 11,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE,
  [684] = 5,
    STATE(21), 1,
      sym_operator,
    STATE(24), 1,
      aux_sym__ws,
    ACTIONS(127), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(125), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(29), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [708] = 2,
    ACTIONS(119), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(117), 11,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE,
  [726] = 5,
    STATE(16), 1,
      sym_operator,
    STATE(35), 1,
      aux_sym__ws,
    ACTIONS(127), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(125), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(129), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [750] = 2,
    ACTIONS(123), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(121), 11,
      anon_sym_RBRACK,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [768] = 2,
    ACTIONS(133), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 11,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE,
  [786] = 5,
    STATE(19), 1,
      sym_operator,
    STATE(41), 1,
      aux_sym__ws,
    ACTIONS(127), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(125), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(135), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [810] = 5,
    STATE(23), 1,
      sym_operator,
    STATE(24), 1,
      aux_sym__ws,
    ACTIONS(127), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(125), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(29), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [834] = 4,
    ACTIONS(137), 2,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
    ACTIONS(144), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(142), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(139), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [856] = 2,
    ACTIONS(133), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 11,
      anon_sym_RBRACK,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [874] = 4,
    ACTIONS(137), 1,
      ts_builtin_sym_end,
    ACTIONS(144), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(142), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(139), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [895] = 7,
    ACTIONS(13), 1,
      aux_sym_number_token1,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(146), 1,
      anon_sym_AT,
    ACTIONS(148), 1,
      sym_quoted,
    STATE(31), 1,
      sym_ref,
    STATE(89), 1,
      aux_sym_ref_repeat1,
    STATE(90), 4,
      sym__bvalue,
      sym_number,
      sym_var,
      sym_ref_for,
  [920] = 7,
    ACTIONS(13), 1,
      aux_sym_number_token1,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(146), 1,
      anon_sym_AT,
    ACTIONS(150), 1,
      sym_quoted,
    STATE(31), 1,
      sym_ref,
    STATE(89), 1,
      aux_sym_ref_repeat1,
    STATE(87), 4,
      sym__bvalue,
      sym_number,
      sym_var,
      sym_ref_for,
  [945] = 7,
    ACTIONS(13), 1,
      aux_sym_number_token1,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(146), 1,
      anon_sym_AT,
    ACTIONS(152), 1,
      sym_quoted,
    STATE(31), 1,
      sym_ref,
    STATE(89), 1,
      aux_sym_ref_repeat1,
    STATE(115), 4,
      sym__bvalue,
      sym_number,
      sym_var,
      sym_ref_for,
  [970] = 4,
    STATE(14), 1,
      aux_sym__ws,
    STATE(48), 1,
      aux_sym__list_repeat1,
    ACTIONS(154), 2,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
    ACTIONS(156), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [988] = 4,
    STATE(3), 1,
      aux_sym__ws,
    STATE(48), 1,
      aux_sym__list_repeat1,
    ACTIONS(53), 2,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
    ACTIONS(159), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [1006] = 4,
    STATE(4), 1,
      aux_sym__ws,
    STATE(48), 1,
      aux_sym__list_repeat1,
    ACTIONS(27), 2,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
    ACTIONS(161), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [1024] = 4,
    STATE(2), 1,
      aux_sym__ws,
    STATE(50), 1,
      aux_sym__list_repeat1,
    ACTIONS(55), 2,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
    ACTIONS(163), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [1042] = 4,
    STATE(4), 1,
      aux_sym__ws,
    STATE(49), 1,
      aux_sym__list_repeat1,
    ACTIONS(27), 2,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
    ACTIONS(161), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [1060] = 4,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    STATE(12), 1,
      aux_sym__ws,
    STATE(57), 1,
      aux_sym__list_repeat1,
    ACTIONS(165), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [1077] = 4,
    ACTIONS(154), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      aux_sym__ws,
    STATE(54), 1,
      aux_sym__list_repeat1,
    ACTIONS(167), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [1094] = 2,
    ACTIONS(172), 1,
      anon_sym_PIPE,
    ACTIONS(170), 7,
      anon_sym_RBRACK,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_RBRACE,
  [1107] = 2,
    ACTIONS(176), 1,
      sym_identifier,
    ACTIONS(174), 7,
      anon_sym_RBRACK,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_RBRACE,
  [1120] = 4,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      aux_sym__ws,
    STATE(54), 1,
      aux_sym__list_repeat1,
    ACTIONS(178), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [1137] = 4,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      aux_sym__ws,
    STATE(60), 1,
      aux_sym__list_repeat1,
    ACTIONS(180), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [1154] = 2,
    ACTIONS(176), 1,
      sym_identifier,
    ACTIONS(182), 7,
      anon_sym_RBRACK,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_RBRACE,
  [1167] = 4,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    STATE(12), 1,
      aux_sym__ws,
    STATE(54), 1,
      aux_sym__list_repeat1,
    ACTIONS(165), 5,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [1184] = 1,
    ACTIONS(184), 7,
      anon_sym_RBRACK,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_RBRACE,
  [1194] = 1,
    ACTIONS(186), 7,
      anon_sym_RBRACK,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_RBRACE,
  [1204] = 1,
    ACTIONS(188), 7,
      anon_sym_RBRACK,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_RBRACE,
  [1214] = 1,
    ACTIONS(190), 7,
      anon_sym_RBRACK,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_RBRACE,
  [1224] = 1,
    ACTIONS(192), 7,
      anon_sym_RBRACK,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_RBRACE,
  [1234] = 2,
    ACTIONS(176), 1,
      sym_identifier,
    ACTIONS(182), 6,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [1246] = 1,
    ACTIONS(194), 7,
      anon_sym_RBRACK,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_RBRACE,
  [1256] = 2,
    ACTIONS(196), 1,
      anon_sym_PIPE,
    ACTIONS(170), 6,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [1268] = 2,
    ACTIONS(176), 1,
      sym_identifier,
    ACTIONS(174), 6,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [1280] = 1,
    ACTIONS(198), 7,
      anon_sym_RBRACK,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_RBRACE,
  [1290] = 1,
    ACTIONS(154), 7,
      anon_sym_RBRACK,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_RBRACE,
  [1300] = 1,
    ACTIONS(200), 7,
      anon_sym_RBRACK,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_RBRACE,
  [1310] = 1,
    ACTIONS(202), 7,
      anon_sym_RBRACK,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
      anon_sym_RBRACE,
  [1320] = 1,
    ACTIONS(200), 6,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [1329] = 1,
    ACTIONS(202), 6,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [1338] = 1,
    ACTIONS(186), 6,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [1347] = 1,
    ACTIONS(198), 6,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [1356] = 1,
    ACTIONS(188), 6,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [1365] = 1,
    ACTIONS(184), 6,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [1374] = 1,
    ACTIONS(192), 6,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [1383] = 1,
    ACTIONS(154), 6,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [1392] = 1,
    ACTIONS(194), 6,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [1401] = 1,
    ACTIONS(190), 6,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_TAB,
  [1410] = 3,
    ACTIONS(204), 1,
      sym_identifier,
    STATE(39), 1,
      sym_ref,
    STATE(89), 1,
      aux_sym_ref_repeat1,
  [1420] = 3,
    ACTIONS(206), 1,
      sym_identifier,
    STATE(43), 1,
      sym_ref,
    STATE(88), 1,
      aux_sym_ref_repeat1,
  [1430] = 2,
    ACTIONS(208), 1,
      sym_identifier,
    STATE(86), 1,
      aux_sym_ref_repeat1,
  [1437] = 2,
    ACTIONS(211), 1,
      anon_sym_PIPE,
    STATE(93), 1,
      aux_sym_svalue_repeat1,
  [1444] = 2,
    ACTIONS(213), 1,
      sym_identifier,
    STATE(86), 1,
      aux_sym_ref_repeat1,
  [1451] = 2,
    ACTIONS(215), 1,
      sym_identifier,
    STATE(86), 1,
      aux_sym_ref_repeat1,
  [1458] = 2,
    ACTIONS(217), 1,
      anon_sym_PIPE,
    STATE(91), 1,
      aux_sym_svalue_repeat1,
  [1465] = 2,
    ACTIONS(219), 1,
      anon_sym_PIPE,
    STATE(92), 1,
      aux_sym_svalue_repeat1,
  [1472] = 2,
    ACTIONS(221), 1,
      anon_sym_PIPE,
    STATE(92), 1,
      aux_sym_svalue_repeat1,
  [1479] = 2,
    ACTIONS(224), 1,
      anon_sym_PIPE,
    STATE(92), 1,
      aux_sym_svalue_repeat1,
  [1486] = 1,
    ACTIONS(226), 1,
      ts_builtin_sym_end,
  [1490] = 1,
    ACTIONS(228), 1,
      aux_sym_inline_arithmetic_token1,
  [1494] = 1,
    ACTIONS(230), 1,
      aux_sym_inline_arithmetic_token1,
  [1498] = 1,
    ACTIONS(232), 1,
      sym_identifier,
  [1502] = 1,
    ACTIONS(234), 1,
      sym_identifier,
  [1506] = 1,
    ACTIONS(236), 1,
      anon_sym_PIPE,
  [1510] = 1,
    ACTIONS(238), 1,
      anon_sym_RBRACE,
  [1514] = 1,
    ACTIONS(240), 1,
      sym_identifier,
  [1518] = 1,
    ACTIONS(242), 1,
      ts_builtin_sym_end,
  [1522] = 1,
    ACTIONS(99), 1,
      anon_sym_COLON,
  [1526] = 1,
    ACTIONS(244), 1,
      anon_sym_RBRACK,
  [1530] = 1,
    ACTIONS(246), 1,
      sym_identifier,
  [1534] = 1,
    ACTIONS(248), 1,
      sym_identifier,
  [1538] = 1,
    ACTIONS(250), 1,
      anon_sym_RBRACK,
  [1542] = 1,
    ACTIONS(252), 1,
      anon_sym_PIPE,
  [1546] = 1,
    ACTIONS(254), 1,
      anon_sym_RBRACE,
  [1550] = 1,
    ACTIONS(256), 1,
      anon_sym_RBRACK,
  [1554] = 1,
    ACTIONS(258), 1,
      anon_sym_RBRACK,
  [1558] = 1,
    ACTIONS(260), 1,
      anon_sym_RBRACK,
  [1562] = 1,
    ACTIONS(262), 1,
      anon_sym_RBRACK,
  [1566] = 1,
    ACTIONS(264), 1,
      anon_sym_RBRACK,
  [1570] = 1,
    ACTIONS(266), 1,
      anon_sym_PIPE,
  [1574] = 1,
    ACTIONS(176), 1,
      sym_identifier,
  [1578] = 1,
    ACTIONS(268), 1,
      aux_sym_inline_arithmetic_token1,
  [1582] = 1,
    ACTIONS(270), 1,
      aux_sym_inline_arithmetic_token1,
  [1586] = 1,
    ACTIONS(272), 1,
      sym_identifier,
  [1590] = 1,
    ACTIONS(274), 1,
      sym_identifier,
  [1594] = 1,
    ACTIONS(276), 1,
      anon_sym_RBRACK,
  [1598] = 1,
    ACTIONS(278), 1,
      anon_sym_PIPE,
  [1602] = 1,
    ACTIONS(280), 1,
      sym_identifier,
  [1606] = 1,
    ACTIONS(282), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(16)] = 0,
  [SMALL_STATE(17)] = 55,
  [SMALL_STATE(18)] = 110,
  [SMALL_STATE(19)] = 165,
  [SMALL_STATE(20)] = 220,
  [SMALL_STATE(21)] = 275,
  [SMALL_STATE(22)] = 330,
  [SMALL_STATE(23)] = 385,
  [SMALL_STATE(24)] = 440,
  [SMALL_STATE(25)] = 473,
  [SMALL_STATE(26)] = 499,
  [SMALL_STATE(27)] = 521,
  [SMALL_STATE(28)] = 543,
  [SMALL_STATE(29)] = 565,
  [SMALL_STATE(30)] = 587,
  [SMALL_STATE(31)] = 606,
  [SMALL_STATE(32)] = 627,
  [SMALL_STATE(33)] = 648,
  [SMALL_STATE(34)] = 666,
  [SMALL_STATE(35)] = 684,
  [SMALL_STATE(36)] = 708,
  [SMALL_STATE(37)] = 726,
  [SMALL_STATE(38)] = 750,
  [SMALL_STATE(39)] = 768,
  [SMALL_STATE(40)] = 786,
  [SMALL_STATE(41)] = 810,
  [SMALL_STATE(42)] = 834,
  [SMALL_STATE(43)] = 856,
  [SMALL_STATE(44)] = 874,
  [SMALL_STATE(45)] = 895,
  [SMALL_STATE(46)] = 920,
  [SMALL_STATE(47)] = 945,
  [SMALL_STATE(48)] = 970,
  [SMALL_STATE(49)] = 988,
  [SMALL_STATE(50)] = 1006,
  [SMALL_STATE(51)] = 1024,
  [SMALL_STATE(52)] = 1042,
  [SMALL_STATE(53)] = 1060,
  [SMALL_STATE(54)] = 1077,
  [SMALL_STATE(55)] = 1094,
  [SMALL_STATE(56)] = 1107,
  [SMALL_STATE(57)] = 1120,
  [SMALL_STATE(58)] = 1137,
  [SMALL_STATE(59)] = 1154,
  [SMALL_STATE(60)] = 1167,
  [SMALL_STATE(61)] = 1184,
  [SMALL_STATE(62)] = 1194,
  [SMALL_STATE(63)] = 1204,
  [SMALL_STATE(64)] = 1214,
  [SMALL_STATE(65)] = 1224,
  [SMALL_STATE(66)] = 1234,
  [SMALL_STATE(67)] = 1246,
  [SMALL_STATE(68)] = 1256,
  [SMALL_STATE(69)] = 1268,
  [SMALL_STATE(70)] = 1280,
  [SMALL_STATE(71)] = 1290,
  [SMALL_STATE(72)] = 1300,
  [SMALL_STATE(73)] = 1310,
  [SMALL_STATE(74)] = 1320,
  [SMALL_STATE(75)] = 1329,
  [SMALL_STATE(76)] = 1338,
  [SMALL_STATE(77)] = 1347,
  [SMALL_STATE(78)] = 1356,
  [SMALL_STATE(79)] = 1365,
  [SMALL_STATE(80)] = 1374,
  [SMALL_STATE(81)] = 1383,
  [SMALL_STATE(82)] = 1392,
  [SMALL_STATE(83)] = 1401,
  [SMALL_STATE(84)] = 1410,
  [SMALL_STATE(85)] = 1420,
  [SMALL_STATE(86)] = 1430,
  [SMALL_STATE(87)] = 1437,
  [SMALL_STATE(88)] = 1444,
  [SMALL_STATE(89)] = 1451,
  [SMALL_STATE(90)] = 1458,
  [SMALL_STATE(91)] = 1465,
  [SMALL_STATE(92)] = 1472,
  [SMALL_STATE(93)] = 1479,
  [SMALL_STATE(94)] = 1486,
  [SMALL_STATE(95)] = 1490,
  [SMALL_STATE(96)] = 1494,
  [SMALL_STATE(97)] = 1498,
  [SMALL_STATE(98)] = 1502,
  [SMALL_STATE(99)] = 1506,
  [SMALL_STATE(100)] = 1510,
  [SMALL_STATE(101)] = 1514,
  [SMALL_STATE(102)] = 1518,
  [SMALL_STATE(103)] = 1522,
  [SMALL_STATE(104)] = 1526,
  [SMALL_STATE(105)] = 1530,
  [SMALL_STATE(106)] = 1534,
  [SMALL_STATE(107)] = 1538,
  [SMALL_STATE(108)] = 1542,
  [SMALL_STATE(109)] = 1546,
  [SMALL_STATE(110)] = 1550,
  [SMALL_STATE(111)] = 1554,
  [SMALL_STATE(112)] = 1558,
  [SMALL_STATE(113)] = 1562,
  [SMALL_STATE(114)] = 1566,
  [SMALL_STATE(115)] = 1570,
  [SMALL_STATE(116)] = 1574,
  [SMALL_STATE(117)] = 1578,
  [SMALL_STATE(118)] = 1582,
  [SMALL_STATE(119)] = 1586,
  [SMALL_STATE(120)] = 1590,
  [SMALL_STATE(121)] = 1594,
  [SMALL_STATE(122)] = 1598,
  [SMALL_STATE(123)] = 1602,
  [SMALL_STATE(124)] = 1606,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__list, 2),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__list, 4),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__list, 3),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__list, 1),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__ws, 2),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__ws, 2), SHIFT_REPEAT(24),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__ws, 2),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__ws, 2), SHIFT_REPEAT(25),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref, 1, .production_id = 1),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ref, 1, .production_id = 1),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref, 2, .production_id = 4),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ref, 2, .production_id = 4),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator, 1),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bvalue, 1),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__bvalue, 1),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var, 2),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var, 2),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref_for, 3, .production_id = 7),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ref_for, 3, .production_id = 7),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__rvalue, 1),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__lvalue, 1), REDUCE(sym__rvalue, 1),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lvalue, 1),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__lvalue, 1),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__list_repeat1, 2),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__list_repeat1, 2), SHIFT_REPEAT(14),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [167] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__list_repeat1, 2), SHIFT_REPEAT(15),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_svalue, 2, .production_id = 3),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_svalue, 8, .production_id = 3),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_svalue, 7, .production_id = 3),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 4, .production_id = 9),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_list, 5, .production_id = 10),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 5, .production_id = 11),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 3, .production_id = 6),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_arithmetic2, 3),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 4, .production_id = 8),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_arithmetic, 3),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 1),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [208] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ref_repeat1, 2, .production_id = 5), SHIFT_REPEAT(103),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [221] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_svalue_repeat1, 2), SHIFT_REPEAT(116),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [226] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_svalue_repeat1, 4),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ref_repeat1, 2, .production_id = 2),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_cw(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
